ver: 1
max-attempts: 3
debug: false
config:
  prefix: AuthAnvilLogin
  isRequestUpper: true
  checkLowestPassword: true
  checkLongestPassword: true
  enableAgreement: true
  delay-time: 45L
  close-kick: true
materials:
  login:
    left: "PAPER"
    right: "REDSTONE"
    output: "ARROW"
  register:
    left: "DIAMOND"
    right: "IRON_INGOT"
    output: "ARROW"
messages:
  link: "www.bing.com"
  # Login window
  login-title: "Login"
  login-button: "Login"
  login-password-title: "Password"
  login-password-placeholder: "Please enter your password"
  wrong-password: "&cIncorrect password, please try again"
  # Registration window
  reg-title: "Register"
  reg-button: "Register Now"
  reg-password-title: "Password"
  reg-password-placeholder: "Please enter your password"
  reg-confirmPassword-title: "Confirm Password"
  reg-confirmPassword-placeholder: "Please enter your password again"
  passwords-not-match: "&cPasswords do not match, please try again"
  password-empty: "&cPassword cannot be empty, please try again"
  # General prompts
  close-window: "&cWindow closed, login/registration terminated"
  #Failed
  failed: "Failed to open"
agreement:
  -   "1. 用户行为规范:"
  -   "禁止发布不当内容:"
  -   服务器条款通常禁止发布色情、暴力、种族歧视、欺凌等不当内容，以及侵犯他人知识产权的内容.
  -   "禁止作弊和恶意行为:"
  -   服务器条款禁止使用任何作弊手段、利用漏洞、恶意破坏服务器等行为.
  -   "禁止广告和商业行为:"
  -   服务器条款通常禁止在服务器内进行广告宣传、未经授权的商业活动等.
  -   "遵守游戏规则:"
  -   玩家需要遵守《我的世界》官方的游戏规则和服务器的特定规则.
  -   "2. 服务器运营商的责任:"
  -   "提供安全稳定的服务器环境:"
  -   服务器运营商需要保证服务器的正常运行，并采取措施防止作弊、恶意攻击等行为.
  -   "保护用户隐私:"
  -  服务器运营商需要保护玩家的个人信息，不得泄露给未经授权的第三方.
  -   "公平公正地处理违规行为:"
  -   服务器运营商需要对违规行为进行调查和处理，确保服务器环境的公平和健康.
  -   "3. 法律责任:"
  -   "侵权责任:"
  -   玩家发布的内容如果侵犯了他人的知识产权或其他权益，需要承担相应的法律责任.
  -   "违约责任:"
  -   玩家违反服务器条款，可能会被服务器运营商采取封禁账号、移除物品等措施，并可能承担相应的违约责任.
  -   "其他法律责任:"
  -   根据具体情况，玩家还可能需要承担其他法律责任，例如诽谤、侵犯名誉等.
  -   "4. 其他重要条款:"